typography_spectrum: 0.38568
color:
  brandColors:
    - '#ffffff'
    - '#057cc0'
    - '#add5ea'
    - '#cee6f1'
    - '#6ba9d6'
  brandStrength: 0.8125
  lightness: 0.4721774666104466
  saturation: 0.1556363662239164
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23836
analytics:
  google: null
  facebook: null
  twitter: null
name: Astonish
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Astonish Systems
description: Astonish Email
purpose: []
