name: Astonish
favicon: null
layout_spectrum: 0.04647292289882898
typography_spectrum: 0.9667601007968187
title: Astonish Systems
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6360886199399829
  lightness: 0.4721774666104466
  saturation: 0.1556363662239164
  rhythmicContrast: 0.01968693220987916
purpose: []
